### ISSUE TITLE
How to create titles???

### ISSUE THREAD

**Issue by stampylongr** [uiiverse/Uiiverse#2]
Yeah, I tried to create a title, but it won't show up in the titles list page. What do each of the variables do?

**Comment by chaiaia** [comment]
Seconded. Is it through the admin panel?

**Comment by stampylongr** [comment]
@chaiaia It's not through the admin panel, I can tell you that. I have an instance running, and access to the admin panel. It's not there. All that's there is banning, verifying, changing passwords, and deleting posts/comments.

**Comment by BashfulWizard** [comment]
What do you mean create a title? Do you mean creating a new community?

**Comment by stampylongr** [comment]
@realFunnyBone Yeah, that was what I meant. I referred to it as 'titles' as that is what communities are referred to in the DB.

**Comment by BashfulWizard** [comment]
You can clone an existing community database and change the values in phpMyAdmin.

**Comment by stampylongr** [comment]
There were no communities, though.
![Screenshot 2019-10-15 at 8 22 29 PM](https://user-images.githubusercontent.com/42777835/66878798-8dcb9c00-ef89-11e9-88d5-006be7b7c862.png)

**Comment by BashfulWizard** [comment]
You're looking at the old database I think...

**Comment by stampylongr** [comment]
I just imported the `DatabaseStructure.sql` file from the repo. Did I do something wrong?

**Comment by BashfulWizard** [comment]
wait im confused, is this a clone **YOU'RE** making?

**Comment by stampylongr** [comment]
No, it's a private clone, for testing purposes only (a.k.a. just for me messing around).

**Comment by BashfulWizard** [comment]
thats what I meant. I could send you a template of a community for you to use.

**Comment by stampylongr** [comment]
Ah, okay. I would appreciate it, if you don't mind.

**Comment by BashfulWizard** [comment]
https://send.firefox.com/download/9dc65779274cf185/#5FpkMhuMStnZ20dzylClwQ

**Comment by stampylongr** [comment]
thanks.
