### ISSUE TITLE
Headers and other things are broken on help pages; Possible CSS Issues???

### ISSUE THREAD

**Issue by stampylongr** [uiiverse/Uiiverse#3]
On my "playground," (and on the official Uiiverse website) the formatting on the help pages (such as the headers and the scrolling) is broken.
Are there any possible solutions?

**Comment by stampylongr** [comment]
For why I have a playground, see:

> No, it's a private clone, for testing purposes only (a.k.a. just for me messing around).

_Originally posted by @stampylongr in https://github.com/uiiverse/Uiiverse/issues/2#issuecomment-542458737_

**Comment by j0lol** [comment]
just reload on the pages and that fixes it

**Comment by stampylongr** [comment]
Thanks!

**Comment by stampylongr** [comment]
Yeah, it worked for a while, and then I added test users and it broke again.
![Screenshot 2019-10-17 at 12 05 46 PM](https://user-images.githubusercontent.com/42777835/67026785-7a7a1700-f0d6-11e9-998f-35b45227f255.png)

**Comment by BashfulWizard** [comment]
yeah its an issue with sessions, you have to refresh.
