### ISSUE TITLE
Will Not Let Me Set Custom Avatar

### ISSUE THREAD

**Issue by stampylongr** [uiiverse/Uiiverse#4]
Whenever I set a custom avatar (see 1st attached photo for proof):

- Avatar will not show up in icon spot
- See 2nd attached image.
![Screenshot 2019-12-06 at 2 45 27 PM](https://user-images.githubusercontent.com/42777835/70351567-36ce9e80-1837-11ea-98a4-6eb0e33e05a4.png)
![Screenshot 2019-12-06 at 2 49 40 PM](https://user-images.githubusercontent.com/42777835/70351775-a9d81500-1837-11ea-8c25-d3ca6c4bda55.png)

Why is this happening?

**Comment by wiredsis** [comment]
Hi. It has to be a i.imgur.com image for security reasons.

**Comment by stampylongr** [comment]
Ah, okay. Thanks!
